// <auto-generated />
using FoodTruck;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodTruck.Migrations
{
    [DbContext(typeof(FoodTruckDbContext))]
    [Migration("20221005111135_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodTruck.Models.Database.CupboardStock", b =>
                {
                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Item");

                    b.ToTable("CupboardStock");

                    b.HasData(
                        new
                        {
                            Item = "Egg",
                            Quantity = 0
                        },
                        new
                        {
                            Item = "Garlic",
                            Quantity = 0
                        },
                        new
                        {
                            Item = "Onion",
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("FoodTruck.Models.Database.FridgeStock", b =>
                {
                    b.Property<string>("Item")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Item");

                    b.ToTable("FridgeStock");

                    b.HasData(
                        new
                        {
                            Item = "Beef",
                            Quantity = 0
                        },
                        new
                        {
                            Item = "Butter",
                            Quantity = 0
                        },
                        new
                        {
                            Item = "Cheese",
                            Quantity = 0
                        },
                        new
                        {
                            Item = "Ham",
                            Quantity = 0
                        },
                        new
                        {
                            Item = "Pancetta",
                            Quantity = 0
                        },
                        new
                        {
                            Item = "Pepperoni",
                            Quantity = 0
                        },
                        new
                        {
                            Item = "Pineapple",
                            Quantity = 0
                        },
                        new
                        {
                            Item = "RedChilli",
                            Quantity = 0
                        },
                        new
                        {
                            Item = "TomatoSauce",
                            Quantity = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
